general.import = [
  # uncomment the flavour you want below:
  #"~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
   "~/.config/alacritty/catppuccin-mocha.toml"
]

[terminal]

[terminal.shell]
program = "/bin/bash"
args = ["-c", "fastfetch -c examples/13; exec $SHELL"]
